### PR TITLE
Update Unit tests

### PR DESCRIPTION
**Pull request by On5-Repos**
Update DynamicFieldsTypeTest ... and all tests are successful.

### CODE REVIEW

**Comment by craigh** [comment]
Thank you @On5-Repos 

All tests are passing, but apparently the phpcs-fixer config defaults have changed since the last release so now that is also failing.

I'll merge this anyway. Any chance you want to take a shot at changing the phpcs-fixer config to allow current?

**Comment by On5-Repos** [comment]
If you keep backwards compatibility for php 7.4 then its difficult. with php 8.0 / 8.1 handful of symfony core packages do get updated which are not compatible with 7.4. When i switch to 8.1 and check phpcs-fixer etc everything is good with 14 fixes. but Switching back to 7.4 --- errors regarding packages install are not compatible with 7.4 ... do you want to keep 7.4?

**Comment by craigh** [comment]
I'd like to figure out a way to keep both. I'm sure there must be a way.

**Comment by On5-Repos** [comment]
hey I am sorry been so busy with work i did not had chance to work on this, I will try to do it this week

**Comment by craigh** [comment]
@On5-Repos I'm working on it right now actually. Stay tuned.

**Comment by craigh** [comment]
@On5-Repos released!

**Comment by On5-Repos** [comment]
cool i will review and report back.

**Pull request merged**
